# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Users\Joanna\Desktop\CLion 2023.1.1\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Users\Joanna\Desktop\CLion 2023.1.1\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Joanna\Desktop\Sdizo1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Joanna\Desktop\Sdizo1\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Users\Joanna\Desktop\CLion 2023.1.1\bin\cmake\win\x64\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Users\Joanna\Desktop\CLion 2023.1.1\bin\cmake\win\x64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Joanna\Desktop\Sdizo1\cmake-build-debug\CMakeFiles C:\Users\Joanna\Desktop\Sdizo1\cmake-build-debug\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Joanna\Desktop\Sdizo1\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sdizo1

# Build rule for target.
Sdizo1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Sdizo1
.PHONY : Sdizo1

# fast build rule for target.
Sdizo1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/build
.PHONY : Sdizo1/fast

BinaryHeap.obj: BinaryHeap.cpp.obj
.PHONY : BinaryHeap.obj

# target to build an object file
BinaryHeap.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/BinaryHeap.cpp.obj
.PHONY : BinaryHeap.cpp.obj

BinaryHeap.i: BinaryHeap.cpp.i
.PHONY : BinaryHeap.i

# target to preprocess a source file
BinaryHeap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/BinaryHeap.cpp.i
.PHONY : BinaryHeap.cpp.i

BinaryHeap.s: BinaryHeap.cpp.s
.PHONY : BinaryHeap.s

# target to generate assembly for a file
BinaryHeap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/BinaryHeap.cpp.s
.PHONY : BinaryHeap.cpp.s

CountTime.obj: CountTime.cpp.obj
.PHONY : CountTime.obj

# target to build an object file
CountTime.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/CountTime.cpp.obj
.PHONY : CountTime.cpp.obj

CountTime.i: CountTime.cpp.i
.PHONY : CountTime.i

# target to preprocess a source file
CountTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/CountTime.cpp.i
.PHONY : CountTime.cpp.i

CountTime.s: CountTime.cpp.s
.PHONY : CountTime.s

# target to generate assembly for a file
CountTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/CountTime.cpp.s
.PHONY : CountTime.cpp.s

DoublyLinkedList.obj: DoublyLinkedList.cpp.obj
.PHONY : DoublyLinkedList.obj

# target to build an object file
DoublyLinkedList.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/DoublyLinkedList.cpp.obj
.PHONY : DoublyLinkedList.cpp.obj

DoublyLinkedList.i: DoublyLinkedList.cpp.i
.PHONY : DoublyLinkedList.i

# target to preprocess a source file
DoublyLinkedList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/DoublyLinkedList.cpp.i
.PHONY : DoublyLinkedList.cpp.i

DoublyLinkedList.s: DoublyLinkedList.cpp.s
.PHONY : DoublyLinkedList.s

# target to generate assembly for a file
DoublyLinkedList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/DoublyLinkedList.cpp.s
.PHONY : DoublyLinkedList.cpp.s

DynamicArray.obj: DynamicArray.cpp.obj
.PHONY : DynamicArray.obj

# target to build an object file
DynamicArray.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/DynamicArray.cpp.obj
.PHONY : DynamicArray.cpp.obj

DynamicArray.i: DynamicArray.cpp.i
.PHONY : DynamicArray.i

# target to preprocess a source file
DynamicArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/DynamicArray.cpp.i
.PHONY : DynamicArray.cpp.i

DynamicArray.s: DynamicArray.cpp.s
.PHONY : DynamicArray.s

# target to generate assembly for a file
DynamicArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/DynamicArray.cpp.s
.PHONY : DynamicArray.cpp.s

FileTests.obj: FileTests.cpp.obj
.PHONY : FileTests.obj

# target to build an object file
FileTests.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/FileTests.cpp.obj
.PHONY : FileTests.cpp.obj

FileTests.i: FileTests.cpp.i
.PHONY : FileTests.i

# target to preprocess a source file
FileTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/FileTests.cpp.i
.PHONY : FileTests.cpp.i

FileTests.s: FileTests.cpp.s
.PHONY : FileTests.s

# target to generate assembly for a file
FileTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/FileTests.cpp.s
.PHONY : FileTests.cpp.s

ListNode.obj: ListNode.cpp.obj
.PHONY : ListNode.obj

# target to build an object file
ListNode.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/ListNode.cpp.obj
.PHONY : ListNode.cpp.obj

ListNode.i: ListNode.cpp.i
.PHONY : ListNode.i

# target to preprocess a source file
ListNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/ListNode.cpp.i
.PHONY : ListNode.cpp.i

ListNode.s: ListNode.cpp.s
.PHONY : ListNode.s

# target to generate assembly for a file
ListNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/ListNode.cpp.s
.PHONY : ListNode.cpp.s

RedAndBlackTree.obj: RedAndBlackTree.cpp.obj
.PHONY : RedAndBlackTree.obj

# target to build an object file
RedAndBlackTree.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/RedAndBlackTree.cpp.obj
.PHONY : RedAndBlackTree.cpp.obj

RedAndBlackTree.i: RedAndBlackTree.cpp.i
.PHONY : RedAndBlackTree.i

# target to preprocess a source file
RedAndBlackTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/RedAndBlackTree.cpp.i
.PHONY : RedAndBlackTree.cpp.i

RedAndBlackTree.s: RedAndBlackTree.cpp.s
.PHONY : RedAndBlackTree.s

# target to generate assembly for a file
RedAndBlackTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/RedAndBlackTree.cpp.s
.PHONY : RedAndBlackTree.cpp.s

Test.obj: Test.cpp.obj
.PHONY : Test.obj

# target to build an object file
Test.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/Test.cpp.obj
.PHONY : Test.cpp.obj

Test.i: Test.cpp.i
.PHONY : Test.i

# target to preprocess a source file
Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/Test.cpp.i
.PHONY : Test.cpp.i

Test.s: Test.cpp.s
.PHONY : Test.s

# target to generate assembly for a file
Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/Test.cpp.s
.PHONY : Test.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Sdizo1.dir\build.make CMakeFiles/Sdizo1.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Sdizo1
	@echo ... BinaryHeap.obj
	@echo ... BinaryHeap.i
	@echo ... BinaryHeap.s
	@echo ... CountTime.obj
	@echo ... CountTime.i
	@echo ... CountTime.s
	@echo ... DoublyLinkedList.obj
	@echo ... DoublyLinkedList.i
	@echo ... DoublyLinkedList.s
	@echo ... DynamicArray.obj
	@echo ... DynamicArray.i
	@echo ... DynamicArray.s
	@echo ... FileTests.obj
	@echo ... FileTests.i
	@echo ... FileTests.s
	@echo ... ListNode.obj
	@echo ... ListNode.i
	@echo ... ListNode.s
	@echo ... RedAndBlackTree.obj
	@echo ... RedAndBlackTree.i
	@echo ... RedAndBlackTree.s
	@echo ... Test.obj
	@echo ... Test.i
	@echo ... Test.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

